### PR TITLE
Oceanwater 592 remove qt4 dependency

### PR DESCRIPTION
**Pull request by mogumbo**
This update merges a bunch of small improvements made for VIPER, including removing the qt4 dependency. I will do a similar PR for the ros2 branch.

### CODE REVIEW

**Review by Samahu — APPROVED** [review]
Déjà vu! :eyes:

**Comment by kmdalal** [comment]
Is there a runtime test for this?  And I get this build warning:

Warnings   << irg_gazebo_plugins:cmake /usr/local/home/kdalal/ow/logs/irg_gazebo_plugins/build.cmake.001.log
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  CMakeLists.txt:14 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by mogumbo** [comment]
There's no specific test for these changes in OceanWATERS, but all the changes worked out in VIPER. This merge keeps our irg_open synced with VIPER's.

The build warning you see occurs with the existing melodic-devel branch of irg_open, so that's a separate issue.

**Comment by Samahu** [comment]
> Is there a runtime test for this? And I get this build warning:
> 
> Warnings << irg_gazebo_plugins:cmake /usr/local/home/kdalal/ow/logs/irg_gazebo_plugins/build.cmake.001.log
> CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
> Policy CMP0054 is not set: Only interpret if() arguments as variables or
> keywords when unquoted. Run "cmake --help-policy CMP0054" for policy
> details. Use the cmake_policy command to set the policy and suppress this
> warning.
> 
> Quoted variables like "chrono" will no longer be dereferenced when the
> policy is set to NEW. Since the policy is not set the OLD behavior will be
> used.
> Call Stack (most recent call first):
> /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
> /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
> /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
> CMakeLists.txt:14 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.

You can safely ignore this warning. It is only reported after a clean build.
If you want to totally avoid it .. then just use the following command when you build
```bash
catkin build --cmake-args -Wno-dev
```

**Comment by kmdalal** [comment]
Thanks for the replies.  I made that warning the first entry in a new Caveats section of the user guide.

**Review by kmdalal — APPROVED** [review]

**Pull request merged**
